additionalTrustBundlePolicy: Proxyonly
apiVersion: v1
baseDomain: __BASE_DOMAIN__
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    aws:
      type: __WORKER_TYPE__
  replicas: __WORKER_REPLICAS__
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      type: __CONTROL_PLANE_TYPE__
  replicas: __CONTROL_PLANE_REPLICAS__
metadata:
  creationTimestamp: null
  name: __CLUSTER_NAME__
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: __AWS_REGION__
    vpc: {}
    userTags:
      owner: "__OWNER__"
      purpose: "__PURPOSE__"
      expirationDate: "__EXPIRATION_DATE__"
publish: External
pullSecret: ""
